import Link from "next/link";
import { BookOpen, Rocket, Terminal } from "lucide-react";
import { DocsSidebar, DocsTop } from "@/components/docs-shell";

export default function DocsHome(){
  const quick=[{title:'Quickstart',desc:'Create a project, build a workflow, and inspect your first run.',icon:Rocket,primary:true},{title:'Core concepts',desc:'Understand workflows, agents, runs, artifacts, approvals, and policy.',icon:BookOpen},{title:'CLI setup',desc:'Install the CLI and connect a local workspace.',icon:Terminal}];
  const groups=[['Build','Design workflows','Compose triggers, agents, tools, branches, and approval gates.'],['Build','Configure agents','Set model policy, tool scope, memory, and handoff behavior.'],['Operate','Review runs','Inspect progress, tool activity, failures, and human decisions.'],['Operate','Manage approvals','Require explicit review before sensitive actions continue.'],['Results','Work with artifacts','Review, version, approve, and reuse generated output.'],['Integrate','Connect tools','Bring GitHub, Linear, Slack, MCP servers, and internal APIs into workflows.']];
  return <div className="docs-shell"><DocsTop/><div className="docs-layout"><DocsSidebar/><main className="docs-home"><div className="eyebrow">Documentation</div><h1>Build your first reliable AI workflow.</h1><p className="lead">Start with one workflow, understand the runtime model, then add tools, approvals, artifacts, and team controls as your use case grows.</p><div className="docs-quick">{quick.map(({title,desc,icon:Icon,primary})=><Link className={primary?'primary':''} key={title} href={title==='Quickstart'?'/docs/getting-started':'#'}><span className="docs-quick-icon" aria-hidden="true"><Icon/></span><b>{title}</b><span>{desc}</span></Link>)}</div><section className="docs-section"><h2>Explore Flowbit</h2><div className="link-list">{groups.map(([group,title,desc])=><div className="link-row" key={title}><div><div style={{fontSize:11.5,color:'#8f8a96',marginBottom:3}}>{group}</div><b>{title}</b></div><span>{desc}</span></div>)}</div></section><section className="docs-section"><h2>Common workflows</h2><div className="link-list"><div className="link-row"><b>Release readiness</b><span>Coordinate repository checks, customer signals, launch assets, and approval.</span></div><div className="link-row"><b>Issue triage</b><span>Classify incoming issues, gather context, propose ownership, and surface risky cases.</span></div><div className="link-row"><b>Customer research</b><span>Aggregate calls and support threads into approved product evidence.</span></div></div></section></main></div></div>
}
